version: '3'
services:
  # for development purposes
  dev:
    build: .
    image: "kbc-ex-xero-custom-reports:dev"
    volumes:
        - ./:/code
        - ./data:/data
    command:
      - /bin/sh
